#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and handles SIGTERM

# Handle SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
