#!/usr/bin/env bash
# A Bash script that prints FizzBuzz from 1 to 100

for i in {1..100}; do
  if (( i % 15 == 0 )); then
    printf "FizzBuzz "
  elif (( i % 3 == 0 )); then
    printf "Fizz "
  elif (( i % 5 == 0 )); then
    printf "Buzz "
  else
    printf "%d " "$i"
  fi
done
printf "\n"
