#!/usr/bin/env bash
# Print numbers 1 to 20 with superstitious messages
i=1
while [ "$i" -le 20 ]; do
  case "$i" in
    4)  echo "bad luck from China" ;;
    6)  echo "bad luck from Japan" ;;
    13) echo "superstition" ;;
    15) echo "bad luck from Italy" ;;
    17) echo "good luck" ;;
    19) echo "bad luck from Ethiopia" ;;
    *)  echo "Best School" ;;
  esac
  i=$((i + 1))
done
