#!/usr/bin/env bash
# Loop 1 to 20 using while + case with special messages
i=1
while [ "$i" -le 20 ]; do
  case "$i" in
    4)  echo "bad luck" ;;
    8)  echo "your chance" ;;
    13) echo "superstition" ;;
    *)  echo "$i" ;;
  esac
  i=$((i + 1))
done
